AWSTemplateFormatVersion: "2010-09-09"
Description: Glue Job + IAM Role to Transform CSV Files from Raw to Transformed Layer

Parameters:
  JobName:
    Type: String
    Default: "transform-csv-job"
    Description: Name of the Glue Job

  ScriptLocation:
    Type: String
    Default: "s3://banking-collection-app-datalake-eu-west2/scripts/glue/transform_template.py"
    Description: Full S3 path to Glue ETL script

  BucketName:
    Type: String
    Default: "banking-collection-app-datalake-eu-west2"
    Description: Data lake S3 bucket

  SourcePath:
    Type: String
    Default: "s3://banking-collection-app-datalake-eu-west2/raw/"
    Description: Source Raw Layer Path

  TargetPath:
    Type: String
    Default: "s3://banking-collection-app-datalake-eu-west2/transformed/"
    Description: Transformed Output Path

Resources:

  # -----------------------------------------
  # IAM Role for Glue Job
  # -----------------------------------------
  GlueTransformRole:
    Type: AWS::IAM::Role
    Properties:
      RoleName: "GlueTransformDatalakeRole"
      AssumeRolePolicyDocument:
        Version: "2012-10-17"
        Statement:
          - Effect: Allow
            Principal:
              Service:
                - glue.amazonaws.com
            Action: sts:AssumeRole
      Path: "/"
      ManagedPolicyArns:
        - arn:aws:iam::aws:policy/service-role/AWSGlueServiceRole

  GlueTransformS3Policy:
    Type: AWS::IAM::Policy
    Properties:
      PolicyName: "GlueTransformDataLakeS3Access"
      Roles:
        - !Ref GlueTransformRole
      PolicyDocument:
        Version: "2012-10-17"
        Statement:
          - Effect: Allow
            Action:
              - s3:ListBucket
            Resource: !Sub arn:aws:s3:::${BucketName}
          - Effect: Allow
            Action:
              - s3:GetObject
              - s3:PutObject
              - s3:DeleteObject
            Resource: !Sub arn:aws:s3:::${BucketName}/*

  # -----------------------------------------
  # Glue Job Definition
  # -----------------------------------------
  GlueTransformJob:
    Type: AWS::Glue::Job
    Properties:
      Name: !Ref JobName
      Role: !GetAtt GlueTransformRole.Arn
      GlueVersion: "4.0"
      Command:
        Name: glueetl
        ScriptLocation: !Ref ScriptLocation
        PythonVersion: "3"
      DefaultArguments:
        "--SOURCE_PATH": !Ref SourcePath
        "--TARGET_PATH": !Ref TargetPath
        "--DATASET_NAME": "dim_customer"   # can override at runtime
        "--job-language": "python"
        "--enable-continuous-cloudwatch-log": "true"
        "--enable-metrics": "true"
      ExecutionProperty:
        MaxConcurrentRuns: 1
      MaxRetries: 0
      Timeout: 30

Outputs:
  GlueJobName:
    Description: Glue Job Created
    Value: !Ref JobName

  GlueRoleArn:
    Description: IAM Role Assigned to Glue Job
    Value: !GetAtt GlueTransformRole.Arn
