AWSTemplateFormatVersion: "2010-09-09"
Transform: AWS::Serverless-2016-10-31
Description: ETL Pipeline for Loan Data - Bronze → Silver + Silver → Gold Region Summary Aggregation

Parameters:
  DataLakeBucket:
    Type: String
    Default: banking-collection-app-datalake-eu-west2
    Description: Main S3 bucket for Datalake

Resources:

  LoanETLRole:
    Type: AWS::IAM::Role
    Properties:
      RoleName: LoanETLRole
      AssumeRolePolicyDocument:
        Version: "2012-10-17"
        Statement:
          - Effect: Allow
            Principal:
              Service: lambda.amazonaws.com
            Action: sts:AssumeRole
      Policies:
        - PolicyName: LoanETLAccessPolicy
          PolicyDocument:
            Version: "2012-10-17"
            Statement:
              - Effect: Allow
                Action:
                  - s3:GetObject
                  - s3:ListBucket
                  - s3:PutObject
                  - s3:DeleteObject
                Resource:
                  - !Sub arn:aws:s3:::${DataLakeBucket}
                  - !Sub arn:aws:s3:::${DataLakeBucket}/*
              - Effect: Allow
                Action:
                  - glue:GetDatabase
                  - glue:CreateTable
                  - glue:UpdateTable
                  - glue:GetTable
                  - glue:BatchCreatePartition
                  - glue:CreatePartition
                Resource: "*"
              - Effect: Allow
                Action:
                  - logs:CreateLogGroup
                  - logs:CreateLogStream
                  - logs:PutLogEvents
                Resource: "*"
              - Effect: Allow
                Action:
                  - athena:StartQueryExecution
                  - athena:GetQueryExecution
                  - athena:GetQueryResults
                  - athena:ListQueryExecutions
                Resource: "*"

  LoanDataTransformLambda:
    Type: AWS::Serverless::Function
    Properties:
      FunctionName: loan-data-bronze-to-silver-transform
      Runtime: python3.13
      Handler: lambda_function.lambda_handler
      Role: !GetAtt LoanETLRole.Arn
      Timeout: 150
      MemorySize: 2000
      CodeUri: s3://banking-collection-app-datalake-eu-west2/lambda/lambda_transform_bronze_to_silver.zip
      Layers:
        - arn:aws:lambda:eu-west-2:336392948345:layer:AWSSDKPandas-Python313:4
      Environment:
        Variables:
          BUCKET_NAME: !Ref DataLakeBucket
          BRONZE_PREFIX: Bronze/banking_collections_dataset.csv
          SILVER_PREFIX: Silver/
          ATHENA_DATABASE: loan_analytics

  LoanRegionAggregationLambda:
    Type: AWS::Serverless::Function
    Properties:
      FunctionName: loan-data-silver-to-gold-region-summary
      Runtime: python3.13
      Handler: lambda_function.lambda_handler
      Role: !GetAtt LoanETLRole.Arn
      Timeout: 150
      MemorySize: 2000
      CodeUri: s3://banking-collection-app-datalake-eu-west2/lambda/lambda_transform_silver_to_gold.zip
      Layers:
        - arn:aws:lambda:eu-west-2:336392948345:layer:AWSSDKPandas-Python313:4
      Environment:
        Variables:
          BUCKET_NAME: !Ref DataLakeBucket
          SILVER_PREFIX: Silver/
          GOLD_PREFIX: Gold/
          ATHENA_DATABASE: loan_analytics

Outputs:
  BronzeToSilverLambdaName:
    Description: Bronze → Silver Lambda Function
    Value: !Ref LoanDataTransformLambda

  RegionAggregationLambdaName:
    Description: Silver → Gold Region Summary Lambda Function
    Value: !Ref LoanRegionAggregationLambda

  AthenaDatabaseCreationQuery:
    Description: SQL to run once in Athena to create database
    Value: |
      CREATE DATABASE IF NOT EXISTS loan_analytics;
