AWSTemplateFormatVersion: "2010-09-09"
Description: S3 Data Lake Bucket 

Parameters:
  BucketName:
    Type: String
    Default: "loan-analysis-app-datalake-eu-west2"
    Description: Name of the S3 data lake bucket

Resources:

  # -------------------------
  # S3 Data Lake Bucket
  # -------------------------
  DataLakeBucket:
    Type: AWS::S3::Bucket
    Properties:
      BucketName: !Ref BucketName

Outputs:
  DataLakeBucketName:
    Description: The name of the S3 bucket created
    Value: !Ref DataLakeBucket
