name: Upload files to S3

on:
  push:
    branches:
      - main
    paths:
      - "input/**"
  workflow_dispatch:

jobs:
  upload-to-s3:
    runs-on: ubuntu-latest

    env:
      AWS_REGION: eu-west-2
      DATA_LAKE_BUCKET: loan-analysis-datalake-main  # fixed bucket

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ env.AWS_REGION }}

      - name: Copy files from input/ to S3
        run: |
          aws s3 cp input/ s3://${{ env.DATA_LAKE_BUCKET }}/data/bronze/ --recursive
          echo "✅ Uploaded files to s3://${{ env.DATA_LAKE_BUCKET }}/data/bronze/"
